apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "agent-roi.name" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agent-roi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
